### ISSUE TITLE
Integrate with playlist

### ISSUE THREAD

**Issue by DeadlyEmbrace** [DeadlyEmbrace/MPDN_RemoteControl#13]

**Comment by DeadlyEmbrace** [comment]
Add:
- Show/Hide playlist
- Play next/previous
- Display playlist in remote
- Ability to move items inside the playlist
  -Ability to play any item inside the playlist

**Comment by zachsaw** [comment]
You may want to wait a bit before implementing this as Gartael has some new updates for playlist.

**Comment by DeadlyEmbrace** [comment]
Thanks for the heads up. I'll hang back until the new updates come out as there are some other stuff that needs to be done.
