### ISSUE TITLE
On initial connect playback details aren't updated

### ISSUE THREAD

**Issue by DeadlyEmbrace** [DeadlyEmbrace/MPDN_RemoteControl#16]
If the user need to auth the player then the data isn't correctly passed back.
This probably has to do with the Guid being passed around and either the remote or the extension using the wrong one.

**Comment by zachsaw** [comment]
Is there a way to disable authentication? It's a bit of a hassle when you're using it on a htpc without keyboard or mouse. :)

**Comment by DeadlyEmbrace** [comment]
Will it be allright if I add a disable option in the settings pane?

**Comment by zachsaw** [comment]
Yup that'll do! :)
