### ISSUE TITLE
Enable / disable remote server

### ISSUE THREAD

**Issue by zachsaw** [DeadlyEmbrace/MPDN_RemoteControl#18]
I think we should have it the remote server not enabled by default, seeing as when user runs MPDN it causes a Windows Firewall prompt otherwise. If users are forced to enable it before they could use the remote, it would probably make it easier for them to figure out what the firewall prompt is for.

Cheers,
Zach

**Comment by DeadlyEmbrace** [comment]
That makes sense. I'll look into it over the weekend. Sorry for being so quiet, been a bit busy on another project the past few months.

Cheers,
Deadly

**Comment by DeadlyEmbrace** [comment]
This issue has been fixed in the latest update to the MPDN Extension repo.
