### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by DeadlyEmbrace** [DeadlyEmbrace/MPDN_RemoteControl#7]
Display volume in remote and allow user to set volume.

**Comment by zachsaw** [comment]
For some reason a few things aren't working with the latest code.

I'm not getting Position / Duration updates, Chapters, Audio, Subtitles or Volume at all on the remote client. Status also says connected when MPDN has been closed. Have I broken something on the PlayerExtension side?

Oh, and the Slider thumb appears cut off at the bottom on my Win7 system.

**Comment by DeadlyEmbrace** [comment]
Mmm... I'll take a quick look once I get home.

I'll look into the slider thumb as well, but not going to worry too much for now, once I've integrated all of the controls I'll refactor the UI into something a little more pleasant to look at/use
